name: systeme_anti_vol_v1
description: "Syst_me de sécurité des Engeins avec Arduino"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  animate_do: ^3.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/

fonts:
  - family: JosefinSans
    fonts:
      - assets/fonts/JosefinSans/
